# Generated by Django 4.2.3 on 2023-07-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbrServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='عنوان')),
                ('product', models.TextField(verbose_name='محصول')),
                ('user_name', models.CharField(max_length=255, verbose_name='نام کاربری خریدار')),
                ('amount', models.BigIntegerField(verbose_name='قیمت')),
                ('time', models.DateTimeField(verbose_name='زمان')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='عنوان')),
                ('product', models.TextField(verbose_name='محصول')),
                ('user_name', models.CharField(max_length=255, verbose_name='نام کاربری خریدار')),
                ('amount', models.BigIntegerField(verbose_name='قیمت')),
                ('time', models.DateTimeField(verbose_name='زمان')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.abrserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
